development:
  server: mail.myquotable.com
  port: 26
  domain: myquotable.com
  authentication: login
  username: admin+myquotable.com
  password: Rx6RIX3aXDmI
  
production:
  server: mail.myquotable.com
  port: 26
  domain: myquotable.com
  authentication: login
  username: admin+myquotable.com
  password: Rx6RIX3aXDmI
  tls: true